"""Package the RWF-2000 preparation code into one self-contained Kaggle cell.

A Kaggle notebook cannot reach the local source tree, and this project's
sessions have had neither PyPI nor reliable DNS. So the modules the
preparation needs are compressed into a base64 payload embedded directly
in a single cell: pasting that one cell into the notebook is enough.

The module list is *computed* from the real import graph rather than
hardcoded, so it cannot drift out of date when imports change. The
closure deliberately excludes the temporal/model code, which means the
cell needs only ``cv2`` and ``numpy`` -- both preinstalled on Kaggle --
and never imports torch.

Run::

    python tools/build_kaggle_cell.py

which rewrites ``kaggle_bootstrap_cell.py`` at the repository root.
"""

from __future__ import annotations

import argparse
import ast
import base64
import io
import sys
import zipfile
import zlib
from pathlib import Path
from typing import List, Sequence, Set

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPOSITORY_ROOT / "src"
OUTPUT_FILE = REPOSITORY_ROOT / "kaggle_bootstrap_cell.py"
ENTRY_MODULES = ("rwf2000_kaggle", "rwf2000_validation")

PAYLOAD_MARKER = "__RWF2000_PAYLOAD__"


def local_module_names(source_dir: Path = SOURCE_DIR) -> Set[str]:
    """Return the importable module names inside ``src``."""
    return {path.stem for path in source_dir.glob("*.py")}


def direct_imports(module: str, source_dir: Path, local: Set[str]) -> Set[str]:
    """Return the project-local modules imported by ``module``."""
    tree = ast.parse((source_dir / f"{module}.py").read_text(encoding="utf-8"))
    found: Set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                found.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module:
            name = node.module
            if name.startswith("src."):
                name = name[len("src."):]
            found.add(name.split(".")[0])
    return {name for name in found if name in local}


def required_modules(
    entries: Sequence[str] = ENTRY_MODULES,
    source_dir: Path = SOURCE_DIR,
) -> List[str]:
    """Return the transitive import closure of ``entries``, sorted."""
    local = local_module_names(source_dir)
    seen: Set[str] = set()
    stack = list(entries)
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        stack.extend(direct_imports(current, source_dir, local) - seen)
    return sorted(seen)


def build_payload(modules: Sequence[str], source_dir: Path = SOURCE_DIR) -> str:
    """Return the base64 of a zlib-compressed zip holding ``modules``.

    The zip entries carry a fixed timestamp and mode so the payload is a
    pure function of the module sources. Without that, regenerating would
    produce a different payload every run and the "is the committed cell
    up to date?" check could never be trusted.
    """
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for module in modules:
            info = zipfile.ZipInfo(f"{module}.py", date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(
                info, (source_dir / f"{module}.py").read_text(encoding="utf-8")
            )
    compressed = zlib.compress(buffer.getvalue(), 9)
    return base64.b64encode(compressed).decode("ascii")


CELL_TEMPLATE = r'''# =====================================================================
# RWF-2000 KAGGLE BOOTSTRAP -- run this ONE cell, then stop.
#
# Self-contained: the project modules it needs are embedded below as a
# compressed payload. It needs NO internet, NO PyPI packages (py7zr in
# particular is never used), and no access to the local source tree.
# Only `cv2` and `numpy` are needed, both preinstalled on Kaggle.
#
# Generated by tools/build_kaggle_cell.py -- do not edit by hand.
# =====================================================================
import base64, io, os, shutil, subprocess, sys, zipfile, zlib
from pathlib import Path

# Kaggle defaults; every one can be overridden with an environment
# variable so the same cell can be exercised outside Kaggle.
SRC_DIR       = Path(os.environ.get("RWF_SRC_DIR", "/kaggle/working/_rwf2000_src"))
TARGET        = Path(os.environ.get("RWF_TARGET", "/kaggle/working/rwf2000"))
METADATA      = Path(os.environ.get("RWF_METADATA", "/kaggle/working/rwf2000_metadata"))
SEARCH_ROOTS  = os.environ.get("RWF_SEARCH_ROOTS", "/kaggle/input").split(os.pathsep)
STALE_OUTPUTS = os.environ.get("RWF_STALE", "/kaggle/working/RWF-2000").split(os.pathsep)
CHECK_MD5     = os.environ.get("RWF_SKIP_MD5", "") == ""
FRESH         = os.environ.get("RWF_FRESH", "") != ""

PAYLOAD = "__RWF2000_PAYLOAD__"


def unpack_modules() -> Path:
    """Write the embedded project modules to disk and return their directory."""
    SRC_DIR.mkdir(parents=True, exist_ok=True)
    blob = zlib.decompress(base64.b64decode(PAYLOAD))
    with zipfile.ZipFile(io.BytesIO(blob)) as archive:
        archive.extractall(SRC_DIR)
    return SRC_DIR


def ensure_seven_zip(find_7z) -> str:
    """Return a usable 7-Zip binary, installing p7zip only if necessary.

    Discovery itself is delegated to the project's own ``find_7z`` so the
    rule lives in one place rather than being restated here.
    """
    found = find_7z()
    if found:
        return found
    print("7z not present; attempting a system install (needs network) ...")
    for command in (
        ["apt-get", "-qq", "install", "-y", "p7zip-full"],
        ["apt-get", "-qq", "install", "-y", "p7zip"],
    ):
        try:
            subprocess.run(command, check=False, timeout=300)
        except Exception:
            pass
        found = find_7z()
        if found:
            return found
    raise SystemExit(
        "BLOCKER: no 7-Zip binary is available and p7zip could not be "
        "installed (no network). Attach a p7zip .deb as a Kaggle dataset, "
        "or enable internet for this notebook once."
    )


def drop_stale_outputs() -> None:
    """Remove a previous FAILED extraction that used a different path.

    Only paths named explicitly in STALE_OUTPUTS are touched, and never
    the current target -- a complete dataset is never thrown away here.
    """
    for raw in STALE_OUTPUTS:
        stale = Path(raw.strip())
        if not raw.strip() or not stale.is_dir():
            continue
        if stale.resolve() == TARGET.resolve():
            continue
        print(f"Removing previous incomplete extraction: {stale}")
        shutil.rmtree(stale, ignore_errors=True)


print("=" * 70)
print("RWF-2000 KAGGLE BOOTSTRAP")
print("=" * 70)

source = unpack_modules()
print(f"modules      : {source}")
sys.path.insert(0, str(source))

from rwf2000_kaggle import (  # noqa: E402
    KagglePreparationError,
    bootstrap,
    find_7z,
)

seven_zip = ensure_seven_zip(find_7z)
print(f"7z binary    : {seven_zip}")

drop_stale_outputs()

try:
    ready, report = bootstrap(
        target=TARGET,
        search_roots=SEARCH_ROOTS,
        metadata_dir=METADATA,
        check_md5=CHECK_MD5,
        fresh=FRESH,
        validate=True,
    )
except KagglePreparationError as error:
    print(f"\nBLOCKER: {error}")
    raise SystemExit(1)

print("\n" + "=" * 70)
print("RESULT: READY" if ready else "RESULT: NOT READY")
print("=" * 70)
if ready:
    print(f"dataset root : {report['dataset_root']}")
    print(f"metadata     : {report['manifest_path']}")
    print("\nSTOP HERE. Do not start training in this cell.")
else:
    print("The reconciliation/validation output above names the exact problem.")
'''


def build_cell(
    entries: Sequence[str] = ENTRY_MODULES,
    source_dir: Path = SOURCE_DIR,
) -> str:
    """Return the complete self-contained cell source."""
    modules = required_modules(entries, source_dir)
    payload = build_payload(modules, source_dir)
    return CELL_TEMPLATE.replace(PAYLOAD_MARKER, payload)


def main(argv: Sequence[str] | None = None) -> int:
    """Regenerate the Kaggle bootstrap cell."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(OUTPUT_FILE))
    parser.add_argument("--check", action="store_true",
                        help="Verify the committed cell is up to date.")
    args = parser.parse_args(argv)

    modules = required_modules()
    cell = build_cell()
    output = Path(args.output)

    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != cell:
            print("kaggle_bootstrap_cell.py is STALE; re-run this script.")
            return 1
        print("kaggle_bootstrap_cell.py is up to date.")
        return 0

    output.write_text(cell, encoding="utf-8")
    print(f"modules embedded ({len(modules)}): {', '.join(modules)}")
    print(f"wrote {output} ({len(cell):,} characters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
